// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMldxbhpmJmWimYDA994snN2yC4cbJUHo',
    appId: '1:885236000174:web:207cac6e49442e5849943f',
    messagingSenderId: '885236000174',
    projectId: 'awesomechat-7b5cb',
    authDomain: 'awesomechat-7b5cb.firebaseapp.com',
    databaseURL: 'https://awesomechat-7b5cb-default-rtdb.firebaseio.com',
    storageBucket: 'awesomechat-7b5cb.firebasestorage.app',
    measurementId: 'G-SVM7TQQFV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALRCB-nN_pOsulHwk8VvarFbZhjgh0Yic',
    appId: '1:885236000174:android:b62d20bda986f7b149943f',
    messagingSenderId: '885236000174',
    projectId: 'awesomechat-7b5cb',
    databaseURL: 'https://awesomechat-7b5cb-default-rtdb.firebaseio.com',
    storageBucket: 'awesomechat-7b5cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmEDphCWqPDEoJ_bNR7ihwsaSZrjDUI0A',
    appId: '1:885236000174:ios:11fc63bd1626de5b49943f',
    messagingSenderId: '885236000174',
    projectId: 'awesomechat-7b5cb',
    databaseURL: 'https://awesomechat-7b5cb-default-rtdb.firebaseio.com',
    storageBucket: 'awesomechat-7b5cb.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmEDphCWqPDEoJ_bNR7ihwsaSZrjDUI0A',
    appId: '1:885236000174:ios:11fc63bd1626de5b49943f',
    messagingSenderId: '885236000174',
    projectId: 'awesomechat-7b5cb',
    databaseURL: 'https://awesomechat-7b5cb-default-rtdb.firebaseio.com',
    storageBucket: 'awesomechat-7b5cb.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMldxbhpmJmWimYDA994snN2yC4cbJUHo',
    appId: '1:885236000174:web:af606c55b8c2016249943f',
    messagingSenderId: '885236000174',
    projectId: 'awesomechat-7b5cb',
    authDomain: 'awesomechat-7b5cb.firebaseapp.com',
    databaseURL: 'https://awesomechat-7b5cb-default-rtdb.firebaseio.com',
    storageBucket: 'awesomechat-7b5cb.firebasestorage.app',
    measurementId: 'G-TK4T19Q77H',
  );

}